# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qC_5A93lzb7PN6XVSKCTJaQLFhE89EkI

# Total cost calculator
"""

def calculate_total_cost_and_compare_budget():
    # Define the prices of three items
    item1_price = float(input("Enter the price of item 1: $"))
    item2_price = float(input("Enter the price of item 2: $"))
    item3_price = float(input("Enter the price of item 3: $"))

    # Define the total budget
    budget = float(input("Enter your total budget: $"))

    # Calculate the total cost of the items
    total_cost = item1_price + item2_price + item3_price

    # Compare the total cost with the budget
    print(f"\nThe total cost of the items is: ${total_cost:.2f}")
    print(f"Your total budget is: ${budget:.2f}")

    # Calculate the difference (how much money is left or how much more is needed)
    if total_cost > budget:
        difference = total_cost - budget
        print(f"You need an additional ${difference:.2f} to cover the cost.")
    elif total_cost < budget:
        difference = budget - total_cost
        print(f"You have ${difference:.2f} left after purchasing the items.")
    else:
        print("You have exactly enough money to cover the cost!")

# Call the function
calculate_total_cost_and_compare_budget()